# Generated by Django 5.2.8 on 2025-11-26 03:49

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='DataSource',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('source_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='数据源编码')),
                ('source_name', models.CharField(max_length=100, verbose_name='数据源名称')),
                ('source_type', models.SmallIntegerField(choices=[(1, 'API接口'), (2, '数据库'), (3, '文件')], db_index=True, default=1, verbose_name='数据源类型')),
                ('industry_type', models.SmallIntegerField(choices=[(1, '气象'), (2, '危化'), (3, '防汛'), (4, '交通运输'), (5, '森林火灾')], db_index=True, verbose_name='行业类型')),
                ('api_url', models.CharField(blank=True, help_text='API类型', max_length=500, null=True, verbose_name='API接口地址')),
                ('api_method', models.CharField(blank=True, default='GET', max_length=10, null=True, verbose_name='HTTP方法')),
                ('api_params', models.TextField(blank=True, help_text='JSON格式', null=True, verbose_name='API请求参数')),
                ('db_host', models.CharField(blank=True, help_text='数据库类型', max_length=100, null=True, verbose_name='数据库主机')),
                ('db_port', models.IntegerField(blank=True, help_text='数据库类型', null=True, verbose_name='数据库端口')),
                ('db_name', models.CharField(blank=True, help_text='数据库类型', max_length=100, null=True, verbose_name='数据库名称')),
                ('db_user', models.CharField(blank=True, help_text='数据库类型', max_length=100, null=True, verbose_name='数据库用户名')),
                ('db_password', models.CharField(blank=True, help_text='数据库类型，加密存储', max_length=255, null=True, verbose_name='数据库密码（加密）')),
                ('db_table', models.CharField(blank=True, help_text='数据库类型', max_length=100, null=True, verbose_name='数据表名')),
                ('sync_interval', models.IntegerField(blank=True, default=60, null=True, verbose_name='同步间隔（分钟）')),
                ('last_sync_at', models.DateTimeField(blank=True, null=True, verbose_name='最后同步时间')),
                ('status', models.SmallIntegerField(db_index=True, default=1, help_text='0-禁用，1-启用', verbose_name='状态')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='数据源描述')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '数据源',
                'verbose_name_plural': '数据源',
                'db_table': 'data_sources',
                'indexes': [models.Index(fields=['source_type'], name='data_source_source__b1a60c_idx'), models.Index(fields=['industry_type'], name='data_source_industr_ac39dc_idx'), models.Index(fields=['status'], name='data_source_status_1e5c21_idx')],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('template_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='模板编码')),
                ('template_name', models.CharField(max_length=100, verbose_name='模板名称')),
                ('template_type', models.SmallIntegerField(choices=[(1, '系统消息'), (2, '短信'), (3, '邮件')], db_index=True, default=1, verbose_name='模板类型')),
                ('message_type', models.SmallIntegerField(choices=[(1, '预警通知'), (2, '报警通知'), (3, '简报推送'), (4, '叫应通知'), (5, '其他')], db_index=True, default=1, verbose_name='消息类型')),
                ('subject', models.CharField(blank=True, help_text='邮件类型', max_length=200, null=True, verbose_name='消息主题')),
                ('content', models.TextField(help_text='支持变量占位符，如：{变量名}', verbose_name='消息内容')),
                ('variables', models.TextField(blank=True, help_text='JSON格式，说明可用变量', null=True, verbose_name='变量说明')),
                ('status', models.SmallIntegerField(db_index=True, default=1, help_text='0-禁用，1-启用', verbose_name='状态')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='模板描述')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '消息模板',
                'verbose_name_plural': '消息模板',
                'db_table': 'message_templates',
                'indexes': [models.Index(fields=['template_type'], name='message_tem_templat_1746ab_idx'), models.Index(fields=['message_type'], name='message_tem_message_aacffb_idx'), models.Index(fields=['status'], name='message_tem_status_9bd291_idx')],
            },
        ),
    ]
