# Generated by Django 5.2.8 on 2025-11-26 03:21

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('org_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='组织编码')),
                ('org_name', models.CharField(max_length=100, verbose_name='组织名称')),
                ('parent_id', models.BigIntegerField(db_index=True, default=0, help_text='0表示顶级组织', verbose_name='父组织ID')),
                ('org_type', models.SmallIntegerField(choices=[(1, '政府部门'), (2, '企业单位'), (3, '事业单位')], db_index=True, default=1, verbose_name='组织类型')),
                ('level', models.IntegerField(default=1, verbose_name='组织层级')),
                ('leader', models.CharField(blank=True, max_length=50, null=True, verbose_name='负责人')),
                ('phone', models.CharField(blank=True, max_length=20, null=True, verbose_name='联系电话')),
                ('address', models.CharField(blank=True, max_length=255, null=True, verbose_name='地址')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='组织描述')),
                ('status', models.SmallIntegerField(db_index=True, default=1, help_text='0-禁用，1-启用', verbose_name='状态')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '组织',
                'verbose_name_plural': '组织',
                'db_table': 'organizations',
                'indexes': [models.Index(fields=['parent_id'], name='organizatio_parent__375f8b_idx'), models.Index(fields=['org_type'], name='organizatio_org_typ_b2fc82_idx'), models.Index(fields=['status'], name='organizatio_status_195db0_idx')],
            },
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('username', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='用户名')),
                ('real_name', models.CharField(blank=True, max_length=50, null=True, verbose_name='真实姓名')),
                ('email', models.CharField(blank=True, db_index=True, max_length=100, null=True, verbose_name='邮箱地址')),
                ('phone', models.CharField(blank=True, db_index=True, max_length=20, null=True, verbose_name='手机号码')),
                ('avatar', models.CharField(blank=True, max_length=255, null=True, verbose_name='头像URL')),
                ('gender', models.SmallIntegerField(choices=[(0, '未知'), (1, '男'), (2, '女')], default=0, verbose_name='性别')),
                ('status', models.SmallIntegerField(db_index=True, default=1, help_text='0-禁用，1-启用', verbose_name='状态')),
                ('last_login_at', models.DateTimeField(blank=True, help_text='自定义最后登录时间字段', null=True, verbose_name='最后登录时间')),
                ('last_login_ip', models.CharField(blank=True, max_length=50, null=True, verbose_name='最后登录IP')),
                ('is_staff', models.BooleanField(default=False, help_text='是否可以访问管理后台', verbose_name='是否为员工')),
                ('is_superuser', models.BooleanField(default=False, verbose_name='是否为超级用户')),
                ('date_joined', models.DateTimeField(default=django.utils.timezone.now, help_text='AbstractBaseUser要求的字段', verbose_name='注册时间')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions')),
                ('organization', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='users', to='users.organization', verbose_name='所属组织')),
            ],
            options={
                'verbose_name': '用户',
                'verbose_name_plural': '用户',
                'db_table': 'users',
            },
        ),
        migrations.CreateModel(
            name='Permission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('permission_code', models.CharField(db_index=True, max_length=100, unique=True, verbose_name='权限编码')),
                ('permission_name', models.CharField(max_length=100, verbose_name='权限名称')),
                ('permission_type', models.SmallIntegerField(choices=[(1, '菜单'), (2, '按钮'), (3, '接口')], db_index=True, default=1, verbose_name='权限类型')),
                ('parent_id', models.BigIntegerField(db_index=True, default=0, help_text='0表示顶级权限', verbose_name='父权限ID')),
                ('path', models.CharField(blank=True, help_text='菜单类型使用', max_length=255, null=True, verbose_name='路由路径')),
                ('component', models.CharField(blank=True, help_text='菜单类型使用', max_length=255, null=True, verbose_name='组件路径')),
                ('icon', models.CharField(blank=True, help_text='菜单类型使用', max_length=100, null=True, verbose_name='图标')),
                ('api_path', models.CharField(blank=True, help_text='接口类型使用', max_length=255, null=True, verbose_name='API路径')),
                ('http_method', models.CharField(blank=True, help_text='GET, POST, PUT, DELETE等', max_length=10, null=True, verbose_name='HTTP方法')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='权限描述')),
                ('status', models.SmallIntegerField(db_index=True, default=1, help_text='0-禁用，1-启用', verbose_name='状态')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '权限',
                'verbose_name_plural': '权限',
                'db_table': 'permissions',
                'indexes': [models.Index(fields=['permission_type'], name='permissions_permiss_1fa87a_idx'), models.Index(fields=['parent_id'], name='permissions_parent__2f4f43_idx'), models.Index(fields=['status'], name='permissions_status_f0891e_idx')],
            },
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='创建时间')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='更新时间')),
                ('deleted_at', models.DateTimeField(blank=True, db_index=True, null=True, verbose_name='删除时间')),
                ('role_code', models.CharField(db_index=True, max_length=50, unique=True, verbose_name='角色编码')),
                ('role_name', models.CharField(max_length=50, verbose_name='角色名称')),
                ('description', models.CharField(blank=True, max_length=255, null=True, verbose_name='角色描述')),
                ('status', models.SmallIntegerField(db_index=True, default=1, help_text='0-禁用，1-启用', verbose_name='状态')),
                ('sort_order', models.IntegerField(default=0, verbose_name='排序顺序')),
                ('remark', models.TextField(blank=True, null=True, verbose_name='备注信息')),
            ],
            options={
                'verbose_name': '角色',
                'verbose_name_plural': '角色',
                'db_table': 'roles',
                'indexes': [models.Index(fields=['status'], name='roles_status_86510b_idx')],
            },
        ),
        migrations.CreateModel(
            name='UserRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to='users.role')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_roles', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '用户角色关联',
                'verbose_name_plural': '用户角色关联',
                'db_table': 'user_roles',
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(related_name='users', through='users.UserRole', to='users.role', verbose_name='角色'),
        ),
        migrations.CreateModel(
            name='RolePermission',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='创建时间')),
                ('permission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.permission')),
                ('role', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='role_permissions', to='users.role')),
            ],
            options={
                'verbose_name': '角色权限关联',
                'verbose_name_plural': '角色权限关联',
                'db_table': 'role_permissions',
                'indexes': [models.Index(fields=['role'], name='role_permis_role_id_0ea48f_idx'), models.Index(fields=['permission'], name='role_permis_permiss_96a6c9_idx')],
                'unique_together': {('role', 'permission')},
            },
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['user'], name='user_roles_user_id_05df60_idx'),
        ),
        migrations.AddIndex(
            model_name='userrole',
            index=models.Index(fields=['role'], name='user_roles_role_id_0b583b_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='userrole',
            unique_together={('user', 'role')},
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['email'], name='users_email_4b85f2_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['phone'], name='users_phone_af6883_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['status'], name='users_status_9ca66f_idx'),
        ),
        migrations.AddIndex(
            model_name='user',
            index=models.Index(fields=['organization'], name='users_organiz_ca9165_idx'),
        ),
    ]
